### PR TITLE
added back in windows

### PR DESCRIPTION
**Pull request by jbaxleyiii**
# Feature / Fixed Issue(s)
- Added support for windows as a platform

# Screenshots
capture

# QA Process
All new features and fixes should be tested and signed off on in the device testing document that corresponds to this PR. **This PR should be tested and PASS on all devices/breakpoints prior to releasing.**

# Reporting Bugs
If you find an issue, a bug, or something that seems weird, thank you! That is extremely helpful. You can report this kind of feedback using our [GitHub Issues page](https://github.com/NewSpring/Rock-Native/issues). Here are a few things that are great to include in an issue:

- Reference to this pull request.
- Steps to reproduce the issue
- Explanation of the buggy behavior
- Explanation of the expected behavior
- Screenshots of the app if helpful

### CODE REVIEW

**Comment by newspringweb** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by jbaxleyiii** [comment]
@delianides @JakeDawkins @richarddubay could you try pulling this down and running the ios / android versions to make sure this doesn't break them?

**Review by JakeDawkins — APPROVED** [review]
Works on my machine 💯

**Comment by JakeDawkins** [comment]
> Pics or it didn't happen
screen shot 2017-03-30 at 11 52 30 pm
screen shot 2017-03-31 at 12 01 13 am

**Pull request merged**
